### ISSUE TITLE
Response for moderation is appearing twice

### ISSUE THREAD

**Issue by couci** [torchbox/m-response#197] opened 2018-11-20 17:29 UTC
After successfully moderated a response I got the same one to moderate it again.  Screenshots attached
<img width="550" alt="screen shot 2018-11-20 at 18 29 14" src="https://user-images.githubusercontent.com/7702955/48791686-9290bd00-ecf2-11e8-96d7-d65570f7f6ac.png">
<img width="512" alt="screen shot 2018-11-20 at 18 29 21" src="https://user-images.githubusercontent.com/7702955/48791687-9290bd00-ecf2-11e8-8191-5c8e787f4135.png">

**Comment by thehashrocket** [comment] 2018-11-21 19:30
I had this happen to me today as well. I could even leave the page and come back and it was still there. Hitting "skip" on the item seemed to fix it for now.

**Comment by johngian** [comment] 2018-11-27 13:51
I went through all the responses in staging and i couldn't reproduce it. While checking the release logs i figured that this bug was first reported before #195 was pushed to prod so it might be the case that this fixed it.

The only explanation i can give at this point is that it was a race condition between fetching a new response and releasing one. I suggest we close this for now and re-open if this issue gets triggered again.

**Closed by johngian** 2018-11-27 13:51 UTC
